[platformio]
default_envs = adafruit_feather_esp32s3_reversetft

[env:adafruit_feather_esp32s3_reversetft]
platform = espressif32
board = adafruit_feather_esp32s3_reversetft
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUHAL_LOG_LEVEL=ARDUHAL_LOG_LEVEL_NONE
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi
board_build.partitions = default.csv
lib_ldf_mode = deep
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17 -Wall
